server:
  port: 7777
spring:
  datasource:
    username: root
    password: liujie288550
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&&characterEncoding=utf-8&&serverTimezone=Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 2MB
      max_request-size: 5MB

  redis:
    host: 47.120.37.44
    username: default
    password: Liujie
    port: 6379
mybatis-plus:
  configuration:
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto